all:
  hosts:
    "{{ lookup('env', 'ANSIBLE_SERVERS').split(',') }}":
      ansible_connection: ssh
      ansible_user: admin
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_ssh_private_key_file: "{{ lookup('env', 'WORKSPACE')/ansible/ANSIBLE_KEY }}"
