---
- name: Hugo Configaration Test & Integration
  hosts: all
  become: no
  vars:
    workarea: /tmp/hugo
  tasks:
    - name: Test and Integrate
      block:
        - name: Create directory for workarea
          file:
            path: "{{ workarea }}"
            state: directory
            mode: '0755'
        - name: Copy containerfile from runner to tmp
          copy:
            src: "{{ lookup('env', 'WORKSPACE') }}/Containerfile"
            dest: "{{ workarea }}/Containerfile"
        - name: Copy entrypoint.sh from runner to tmp
          copy:
            src: "{{ lookup('env', 'WORKSPACE') }}/entrypoint.sh"
            dest: "{{ workarea }}/entrypoint.sh"
        - name: Build the image
          command: "nerdctl build -t gitea.senworld.in/sen/hugo:latest {{ workarea }}/."
        - name: Push the image
          command: "nerdctl push gitea.senworld.in/sen/hugo:latest" 
      always:
        - name: Cleanup
          file: 
            path: "{{ workarea }}"
            state: absent